on:
  push:
    branches:
      - main
    paths:
      - packages/near-api/**

permissions:
  contents: write

jobs:
  package-commit-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/publish.yml
        with:
          package_path: "./packages/near-api/"
        secrets:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

