on:
  push:
    branches:
      - main
    paths:
      - packages/near-nft-lib/**

permissions:
  contents: write

jobs:
  package-commit-publish:
    uses: ./.github/workflows/publish.yml
    with:
      package_path: "./packages/near-nft-lib/"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

